### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by fosterreproducibleresearch** [OpenBioLink/SAFRAN#5]
We are trying to run SAFRAN on Ubuntu 20.04 for the WN18RR dataset but we are facing the following error:

```./SAFRAN applynoisy config-wn.properties 
ACTION = applynoisy
PATH_TRAINING = ../train.txt
PATH_TEST = ../test.txt
PATH_VALID = ../valid.txt
PATH_RULES = rules_wn/alpha-100
PATH_OUTPUT = rules/safran_wn18rr_rules.txt
WORKER_THREADS = -1
DISCRIMINATION_BOUND = 1000
UNSEEN_NEGATIVE_EXAMPLES = 5
TOP_K_OUTPUT = 10
REFLEXIV_TOKEN = me_myself_i
ONLY_UNCONNECTED = 0
TRIAL = 0

Reading trainingset...
Trainingset read and indexed in 519 ms
Reading rules...
Rules read in 3725 ms
Reading testset...
Testset read in 114 ms
Reading validationset...
Validationset read in 111 ms
Applying rules...
Relation 0/11 _hypernym
Segmentation fault (core dumped)```

**Comment by nomisto** [comment]
Hello, sorry to hear that, I'll look into it. Did you use the prebuilt application or did you build it yourself?

**Comment by fosterreproducibleresearch** [comment]
Hello,

Thank you for the quick reply.

I used the prebuilt application.

**Comment by nomisto** [comment]
Also, to retrace the error, could you if possible share your ruleset (alpha-100)? (You can just drag and drop the file in a comment)

**Comment by fosterreproducibleresearch** [comment]
Here are the first lines of the rules's file

5	3	0.6	_derivationally_related_form(X,00772640) <= _derivationally_related_form(00772640,X)
1852	2	0.0010799136069114472	_derivationally_related_form(X,00772640) <= _derivationally_related_form(X,A)
1977	3	0.0015174506828528073	_has_part(08562243,Y) <= _has_part(Y,A)
7402	2	2.701972439881113E-4	_member_meronym(12097180,Y) <= 
5	2	0.4	_derivationally_related_form(X,05869857) <= _derivationally_related_form(00003553,X)
2	2	1.0	_derivationally_related_form(02676496,Y) <= _derivationally_related_form(Y,02676496)
4	2	0.5	_derivationally_related_form(02676496,Y) <= _derivationally_related_form(Y,00722232)
7402	2	2.701972439881113E-4	_member_meronym(02614788,Y) <= 
2	2	1.0	_derivationally_related_form(14299070,Y) <= _derivationally_related_form(Y,14299070)
29722	3	1.0093533409595585E-4	_derivationally_related_form(00152018,Y) <= 
3	3	1.0	_verb_group(01637982,Y) <= _verb_group(Y,01637982)
309	2	0.006472491909385114	_synset_domain_topic_of(10434160,Y) <= _synset_domain_topic_of(A,Y)
2	2	1.0	_synset_domain_topic_of(10434160,Y) <= _synset_domain_topic_of(10386984,Y)
29722	4	1.3458044546127448E-4	_derivationally_related_form(X,00226071) <= 
1433	2	0.0013956734124214933	_hypernym(X,00020827) <= _hypernym(A,X)

**Comment by nomisto** [comment]
Ah I see! You learned these rules using AnyBURL-JUNO right? This is a newer version of AnyBURL that also learnes rules with no body, like

```
29722 4 1.3458044546127448E-4 _derivationally_related_form(X,00226071) <=
```

which basically includes a baseline probability to the predictions. However SAFRAN currently does not support these as it was developed with the AnyBURL-RE version. So in order to run SAFRAN now I suggest you either learn rules with

+ The AnyBURL-JUNO version with the property `ZERO_RULES_ACTIVE = false` set in the config or
+ The AnyBURL-RE version (probably safer right now I do not know what else they changed in the new version, see *Previous and Special Versions* at https://web.informatik.uni-mannheim.de/AnyBURL/, you can download the jar file here https://web.informatik.uni-mannheim.de/AnyBURL/2020-08/AnyBURL-REX.jar, the configuration should be the same)

or you wait until we implemented these zero body rules, however I cannot say right now when this is.

**Comment by fosterreproducibleresearch** [comment]
Unfortunately, the ZERO_RULES_ACTIVE argument is not recognized

**Comment by fosterreproducibleresearch** [comment]
But it is fine, I have used AnyBURL-RE and it is working. Thanks :)

**Comment by nomisto** [comment]
Sorry, I meant to set it in the config file when learning the rules with AnyBURL, not the config for SAFRAN (f.e. in config-learn.properties file that you use when running `java -Xmx3G -cp AnyBURL-JUNO.jar de.unima.ki.anyburl.LearnReinforced config-learn.properties`). 

Oh perfect!

**Comment by nomisto** [comment]
Closing this now, as I feel this particular issue is resolved for now. Feel free to open it again or create a new issue if you run into further troubles :)
